### ISSUE TITLE
Error: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by tylerzika** [dangmai/prettier-plugin-apex#1201]
The plugin is formatting my apex code in all apex files in dxProjectName > force-app > main > default > classes, except if the file is using a .length() on a string.

The full error from the output tab in vs code:

```
["ERROR" - 9:28:34 AM] Error formatting document.
["ERROR" - 9:28:34 AM] Cannot read properties of undefined (reading 'length')
TypeError: Cannot read properties of undefined (reading 'length')
    at Object.handleNewListInit [as apex.jorje.data.ast.NewObject$NewListInit] (c:\Users\tzika\node_modules\prettier-plugin-apex\dist\src\printer.js:1232:28)
    at genericPrint (c:\Users\tzika\node_modules\prettier-plugin-apex\dist\src\printer.js:2670:38)
    at Object.printGenerically [as print] (c:\Users\tzika\node_modules\prettier-plugin-apex\dist\src\printer.js:2687:17)
    at callPluginPrintFunction (file:///c:/Users/tzika/node_modules/prettier/index.mjs:17846:20)
    at mainPrintInternal (file:///c:/Users/tzika/node_modules/prettier/index.mjs:17829:18)
    at mainPrint (file:///c:/Users/tzika/node_modules/prettier/index.mjs:17812:14)
    at AstPath.call (file:///c:/Users/tzika/node_modules/prettier/index.mjs:16971:14)
    at Object.handleNewExpression [as apex.jorje.data.ast.Expr$NewExpr] (c:\Users\tzika\node_modules\prettier-plugin-apex\dist\src\printer.js:1310:21)
    at genericPrint (c:\Users\tzika\node_modules\prettier-plugin-apex\dist\src\printer.js:2670:38)
    at Object.printGenerically [as print] (c:\Users\tzika\node_modules\prettier-plugin-apex\dist\src\printer.js:2687:17)
```

When I use:

```
npm ls prettier
nom ls prettier-plugin-apex
```

I get:
```
salesforce-app@1.0.0 C:\User\tzika\Documents\projectName
|____ (empty)
```

**Comment by dangmai** [comment]
Could you run

```bash
npm ls -g prettier
npm ls -g prettier-plugin-apex
```

And paste the output here?

Also, if possible could you paste a line of code (with the `length()` method) that's leading to this issue?

**Comment by tylerzika** [comment]
![image](https://github.com/dangmai/prettier-plugin-apex/assets/1011888/29a02dd4-bfb3-4db7-9f11-1adc2518f4c7)

This looks bad 😩

**Comment by tylerzika** [comment]
I removed all calls of length from the class and the formatting error is still happening. There error message has not changed.

**Comment by dangmai** [comment]
The error in your screenshot is fine, I was just checking to see if you have other instances of Prettier or Prettier Apex installed globally.

Is there any chance you could post the class somewhere so I can look at it? If it can't be shared publicly you can email it to me at `contact at dangmai dot net`. It'll help me debugging what's going wrong.

**Comment by dangmai** [comment]
Hmm, now that I'm looking at your folder structure, I think there may be some mismatching version going on between Prettier and Prettier Apex. Your `node_modules` seems to be in `c:\Users\tzika\` while it should be in `C:\User\tzika\Documents\projectName`

Could you try running this:
```
cd c:\Users\tzika\
npm ls prettier
npm ls prettier-plugin-apex
```

**Comment by tylerzika** [comment]
PS C:\Users\tzika> npm ls prettier
npm ERR! code ELSPROBLEMS
npm ERR! invalid: prettier@3.0.3 C:\Users\tzika\node_modules\prettier
tzika@ C:\Users\tzika
├─┬ prettier-plugin-apex@1.13.0
│ └── prettier@3.0.3 deduped invalid: "^2.0.0" from node_modules/prettier-plugin-apex
└── prettier@3.0.3 invalid: "^2.0.0" from node_modules/prettier-plugin-apex


npm ERR! A complete log of this run can be found in: C:\Users\tzika\AppData\Local\npm-cache\_logs\2024-02-12T16_02_53_346Z-debug-0.log
PS C:\Users\tzika> npm ls prettier-plugin-apex
tzika@ C:\Users\tzika
└── prettier-plugin-apex@1.13.0

**Comment by tylerzika** [comment]
I'm seeing `node_modules` in both `C:\Users\tzika` and `C:\Users\tzika\Documents\projectName`

**Comment by tylerzika** [comment]
Deleting the folders in my user folder appeared to fix it. Thanks!

**Comment by dangmai** [comment]
I'm glad you got it figured out! It looks like the root cause is that there's a Prettier `3.0.3` installed, which is incompatible with Prettier Apex `1.13.0`. When you delete the `node_modules`, you're choosing to use the correct version instead.
