### ISSUE TITLE
Cannot read properties of undefined (reading 'unit')

### ISSUE THREAD

**Issue by andrii-solokh** [dangmai/prettier-plugin-apex#1275]
## Self-Troubleshooting Checklist

- [X] Are you running Prettier Apex >= 2.0.0? If Yes, have you gone through the [Upgrade Guide](https://github.com/dangmai/prettier-plugin-apex/wiki/Upgrading-to-Prettier-Apex-v2)?
- [X] Are you running Java < 11? If Yes, you need to install a newer Java version.

## Describe your Issue

```
["INFO" - 11:09:26] Using config file at /Users/me/Projects/Teachiq/.prettierrc
["INFO" - 11:09:27] Formatting file:///Users/me/Projects/Teachiq/src/core-crm/main/default/classes/service/OrdersService.cls
["INFO" - 11:09:27] Using config file at /Users/me/Projects/Teachiq/.prettierrc
["INFO" - 11:09:27] PrettierInstance:
{
  "modulePath": "/Users/me/Projects/Teachiq/node_modules/prettier/index.cjs",
  "importResolver": {},
  "callMethodResolvers": {},
  "currentCallMethodId": 75,
  "version": "3.2.5"
}
["INFO" - 11:09:27] Using ignore file (if present) at /Users/me/Projects/Teachiq/.prettierignore
["INFO" - 11:09:27] File Info:
{
  "ignored": false,
  "inferredParser": "apex"
}
["INFO" - 11:09:27] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 11:09:27] Prettier Options:
{
  "filepath": "/Users/me/Projects/Teachiq/src/core-crm/main/default/classes/service/OrdersService.cls",
  "parser": "apex",
  "trailingComma": "none",
  "printWidth": 120,
  "tabWidth": 4,
  "useTabs": false,
  "plugins": [
    "/Users/me/Projects/Teachiq/node_modules/prettier-plugin-apex/dist/src/index.js",
    "/Users/me/Projects/Teachiq/node_modules/@prettier/plugin-xml/src/plugin.js"
  ]
}
["ERROR" - 11:09:27] Error formatting document.
["ERROR" - 11:09:27] Cannot read properties of undefined (reading 'unit')
TypeError: Cannot read properties of undefined (reading 'unit')
    at AstPath.call (file:///Users/me/Projects/Teachiq/node_modules/prettier/index.mjs:20749:20)
    at genericPrint (file:///Users/me/Projects/Teachiq/node_modules/prettier-plugin-apex/dist/src/printer.js:2685:24)
    at Object.printGenerically [as print] (file:///Users/me/Projects/Teachiq/node_modules/prettier-plugin-apex/dist/src/printer.js:2713:17)
    at callPluginPrintFunction (file:///Users/me/Projects/Teachiq/node_modules/prettier/index.mjs:22303:20)
    at printAstToDoc (file:///Users/me/Projects/Teachiq/node_modules/prettier/index.mjs:22258:22)
    at async coreFormat (file:///Users/me/Projects/Teachiq/node_modules/prettier/index.mjs:22611:14)
    at async formatWithCursor (file:///Users/me/Projects/Teachiq/node_modules/prettier/index.mjs:22809:14)
    at async Module.format2 (file:///Users/me/Projects/Teachiq/node_modules/prettier/index.mjs:24194:25)
["INFO" - 11:09:27] Formatting completed in 34ms.
```

```
npm ls -g prettier-plugin-apex                                                                                
npm ERR! code ENOENT
npm ERR! syscall lstat
npm ERR! path /opt/homebrew/Cellar/node/21.6.2/lib
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, lstat '/opt/homebrew/Cellar/node/21.6.2/lib'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in: /Users/me/.npm/_logs/2024-03-22T09_07_27_910Z-debug-0.log

npm ls -g prettier                                                                                           
npm ERR! code ENOENT
npm ERR! syscall lstat
npm ERR! path /opt/homebrew/Cellar/node/21.6.2/lib
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, lstat '/opt/homebrew/Cellar/node/21.6.2/lib'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ls prettier                                                                                               
teach-iq@1.0.0 /Users/me/Projects/Teachiq
├─┬ @prettier/plugin-xml@3.3.1
│ └── prettier@3.2.5 deduped
├─┬ prettier-plugin-apex@2.1.0
│ └── prettier@3.2.5 deduped
└── prettier@3.2.5

npm ls prettier-plugin-apex                                                                                   
teach-iq@1.0.0 /Users/me/Projects/Teachiq
└── prettier-plugin-apex@2.1.0
```

```sh
# Prettier options (if any):
```

**Additional information (please fill this out)**:

- OS: OS X
- Java Version (you can check this by running `java -version`): [e.g. `openjdk version "11"`]
```
java --version                                                                                                ─╯
java 17.0.10 2024-01-16 LTS
Java(TM) SE Runtime Environment (build 17.0.10+11-LTS-240)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.10+11-LTS-240, mixed mode, sharing)
```

**Comment by dangmai** [comment]
Hi there, when I tried formatting your code at: https://apex.dangmai.net/#N4Ig9gDgLglmB2BnEAuUEwCcqoCy4GYAaEACzERxRAEMIBTADwFobKA6BTe+AE3szsAxmAC2IEhExgoYEQBtUZKFAjJJNTIgFK6TCSCkx4UAOoxeUUqgAcABhJQaAI3OXrKAEwkArtoAqLsgoAGY08tokeowAkkgCUABixuEAcvQA7vLG9KhQmD70AL4kIvxKED7O2UIABBkwVrWIpJrGAOa1QvJsiLUA8pj8WgDKAgBuMEL0tcAAOvC1S7WV1VPNTrB142AWtTRCsOM0UPSDw4gAFGNQADwxvAB8tVjDD4gAlLMLy7-NE1N6JcPuwDkcTmchgIrq8BO8PgBuH7LIoLZFLIzHU4bE7rGLnaFjTCTab-YmA4HfRZ-JbcKA+TCLS74qGjAHTL4AQQgEBquIQ7CJJPo7HgmTilBo8GmzIJbPJ02EPUQnyR1KWqPgRRARSAA I can see that it's formatted without issue, so there's probably some set up issue on your computer.

Are you using Prettier Apex from the command line or from VSCode? If from VSCode, have you tried restarting VSCode yet?

**Comment by andrii-solokh** [comment]
@dangmai 
Thank you for reply.
I'm getting the same error from both VS Code and terminal. 
I've already tried reinstalling prettier and plugin globally/ locally.

```
╰─❯ prettier -w src/core-crm/main/default/classes/selectors/AccessesSelector.cls                                                                   ─╯
src/core-crm/main/default/classes/selectors/AccessesSelector.cls
[error] src/core-crm/main/default/classes/selectors/AccessesSelector.cls: TypeError: Cannot read properties of undefined (reading 'unit')
[error]     at AstPath.call (file:///Users/me/.nvm/versions/node/v20.12.0/lib/node_modules/prettier/index.mjs:20749:20)
[error]     at genericPrint (file:///Users/me/Projects/Teachiq/node_modules/prettier-plugin-apex/dist/src/printer.js:2685:24)
[error]     at Object.printGenerically [as print] (file:///Users/me/Projects/Teachiq/node_modules/prettier-plugin-apex/dist/src/printer.js:2713:17)
[error]     at callPluginPrintFunction (file:///Users/me/.nvm/versions/node/v20.12.0/lib/node_modules/prettier/index.mjs:22303:20)
[error]     at printAstToDoc (file:///Users/me/.nvm/versions/node/v20.12.0/lib/node_modules/prettier/index.mjs:22258:22)
[error]     at async coreFormat (file:///Users/me/.nvm/versions/node/v20.12.0/lib/node_modules/prettier/index.mjs:22611:14)
[error]     at async formatWithCursor (file:///Users/me/.nvm/versions/node/v20.12.0/lib/node_modules/prettier/index.mjs:22809:14)
[error]     at async formatFiles (file:///Users/me/.nvm/versions/node/v20.12.0/lib/node_modules/prettier/internal/cli.mjs:6673:18)
[error]     at async main (file:///Users/me/.nvm/versions/node/v20.12.0/lib/node_modules/prettier/internal/cli.mjs:7081:5)
[error]     at async Module.run (file:///Users/me/.nvm/versions/node/v20.12.0/lib/node_modules/prettier/internal/cli.mjs:7027:5)
```

**Comment by dangmai** [comment]
That's very interesting, I don't think I've seen this issue before. This will require a bit of digging to see what the root cause is.

Do you mind running this command at the root of your project?

```bash
./node_modules/prettier-plugin-apex/vendor/apex-ast-serializer/bin/apex-ast-serializer -f json -i -l src/core-crm/main/default/classes/selectors/AccessesSelector.cls
```

This hopefully would contain some errors that we can go off of to debug this further. The output is basically the Abstract Syntax Tree for the code in your file, if you could share it it'd be great (but I understand if it's proprietary and you can't share it).

**Comment by dangmai** [comment]
Ah yeah I've run into those issues myself (forgetting that I've set environment variables somewhere). I'm glad you got it figured out!

**Comment by alessandroBonzo** [comment]
Hello,
I've been facing the same issue.
I ran the `./node_modules/prettier-plugin-apex/vendor/apex-ast-serializer/bin/apex-ast-serializer -f json -i -l force-app\main\default\classes\ChoosePalletsController.cls` and it worked, no java errors.


These are my prettier versions :

```
npm ls prettier
salesforce-app@1.0.0 C:\Users\aascione\Desktop\Progetti VS\tgroupDEV
├─┬ @prettier/plugin-xml@3.4.1
│ └── prettier@3.2.5 deduped
├─┬ prettier-plugin-apex@2.1.0
│ └── prettier@3.2.5 deduped
└── prettier@3.2.5
```
Let me know if I can give you more infos.
Thanks in advance

**Comment by dangmai** [comment]
@alessandroBonzo this might be a separate issue, do you mind creating another issue for it, and fill out the issue questions? Thank you!
