### ISSUE TITLE
Cannot read properties of undefined (reading 'unit')

### ISSUE THREAD

**Issue by YodaDaCoda** [dangmai/prettier-plugin-apex#1393]
### Self-Troubleshooting Checklist

- [X] Are you running Prettier Apex >= 2.0.0? If Yes, have you gone through the [Upgrade Guide](https://github.com/dangmai/prettier-plugin-apex/wiki/Upgrading-to-Prettier-Apex-v2)?
- [X] Are you running Java >= 11? If No, you need to install a newer Java version.
- [X] Are you running VSCode and recently upgraded Prettier or Prettier Apex? If Yes, have you restarted VSCode after the upgrade?

### Describe your issue

I get a large stack trace when running prettier against any apex file. I'm running it from the terminal in vscode. I'm running Java 17.

```
force-app/main/default/classes/AccountFileGenerator.cls
[error] force-app/main/default/classes/AccountFileGenerator.cls: TypeError: Cannot read properties of undefined (reading 'unit')
[error]     at AstPath.call (file:///Users/ranjitha.sreedhar/Desktop/RTBA/CARRP-11750/Residential%20Tenancies%20Bond%20Authority/node_modules/prettier/index.mjs:20749:20)
[error]     at genericPrint (file:///Users/ranjitha.sreedhar/Desktop/RTBA/CARRP-11750/Residential%20Tenancies%20Bond%20Authority/node_modules/prettier-plugin-apex/dist/src/printer.js:2691:24)
[error]     at Object.printGenerically [as print] (file:///Users/ranjitha.sreedhar/Desktop/RTBA/CARRP-11750/Residential%20Tenancies%20Bond%20Authority/node_modules/prettier-plugin-apex/dist/src/printer.js:2721:17)
[error]     at callPluginPrintFunction (file:///Users/ranjitha.sreedhar/Desktop/RTBA/CARRP-11750/Residential%20Tenancies%20Bond%20Authority/node_modules/prettier/index.mjs:22303:20)
[error]     at printAstToDoc (file:///Users/ranjitha.sreedhar/Desktop/RTBA/CARRP-11750/Residential%20Tenancies%20Bond%20Authority/node_modules/prettier/index.mjs:22258:22)
[error]     at async coreFormat (file:///Users/ranjitha.sreedhar/Desktop/RTBA/CARRP-11750/Residential%20Tenancies%20Bond%20Authority/node_modules/prettier/index.mjs:22611:14)
[error]     at async formatWithCursor (file:///Users/ranjitha.sreedhar/Desktop/RTBA/CARRP-11750/Residential%20Tenancies%20Bond%20Authority/node_modules/prettier/index.mjs:22809:14)
[error]     at async formatFiles (file:///Users/ranjitha.sreedhar/Desktop/RTBA/CARRP-11750/Residential%20Tenancies%20Bond%20Authority/node_modules/prettier/internal/cli.mjs:6673:18)
[error]     at async main (file:///Users/ranjitha.sreedhar/Desktop/RTBA/CARRP-11750/Residential%20Tenancies%20Bond%20Authority/node_modules/prettier/internal/cli.mjs:7081:5)
[error]     at async Module.run (file:///Users/ranjitha.sreedhar/Desktop/RTBA/CARRP-11750/Residential%20Tenancies%20Bond%20Authority/node_modules/prettier/internal/cli.mjs:7027:5)
force-app/main/default/classes/AccountFileGeneratorTest.cls
[error] force-app/main/default/classes/AccountFileGeneratorTest.cls: TypeError: Cannot read properties of undefined (reading 'unit')
[error]     at AstPath.call (file:///Users/ranjitha.sreedhar/Desktop/RTBA/CARRP-11750/Residential%20Tenancies%20Bond%20Authority/node_modules/prettier/index.mjs:20749:20)
[error]     at genericPrint (file:///Users/ranjitha.sreedhar/Desktop/RTBA/CARRP-11750/Residential%20Tenancies%20Bond%20Authority/node_modules/prettier-plugin-apex/dist/src/printer.js:2691:24)
[error]     at Object.printGenerically [as print] (file:///Users/ranjitha.sreedhar/Desktop/RTBA/CARRP-11750/Residential%20Tenancies%20Bond%20Authority/node_modules/prettier-plugin-apex/dist/src/printer.js:2721:17)
force-app/main/default/classes/AddressValidationController.clsnode:events:496
      throw er; // Unhandled 'error' event
      ^
Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
```

### Prettier options (if any)

```shell
e.g. `prettier --write force-app/main/default/classes/AccountFileGenerator.cls`
```

### System Info

```shell
Need to install the following packages:
envinfo@7.13.0
Ok to proceed? (y) y
  System:
    OS: macOS 13.6.7
    CPU: (8) arm64 Apple M1
    Memory: 142.61 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/.volta/tools/image/node/20.11.0/bin/node
    npm: 10.8.0 - ~/.volta/tools/image/node/20.11.0/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash
    Java: 17.0.5 - /usr/bin/javac
    Perl: 5.30.3 - /usr/bin/perl
    Python3: 3.9.6 - /usr/bin/python3
    Ruby: 2.6.10 - /usr/bin/ruby
  npmPackages:
    prettier: ^3.2.5 => 3.2.5
    prettier-plugin-apex: ^2.1.3 => 2.1.3
```

**Comment by dangmai** [comment]
Hi, could you try upgrading to Prettier Apex v2.1.4, then restart Viscose to see if your issue is resolved? There's a speculative fix in there for problems similar to yours.

**Comment by YodaDaCoda** [comment]
🤦 yep that fixed it, thanks mate, sorry i missed the new version

**Comment by dangmai** [comment]
Nice, I'm glad you got it working! 😀
