### ISSUE TITLE
Error Running from Any Context

### ISSUE THREAD

**Issue by msimonis** [dangmai/prettier-plugin-apex#350]
I have prettier and this plugin installed globally, but also tried local to a directory.

**Input:**

```apex
/**
 * @description Example class.
 */
public with sharing class Hello {
    public Hello() {
        System.debug('Hello World');
    }
}
```

**Error:**
```zsh
❯ prettier --write "classes/Hello.cls"                                                        
classes/Hello.cls
[error] classes/Hello.cls: Error: {"apex.jorje.semantic.compiler.parser.ParserOutput": {"@id": "1","internalErrors": [],"parseErrors": [],"unit": {"@class": "apex.jorje.data.ast.CompilationUnit$ClassDeclUnit","@id": "3","body": {"@class": "apex.jorje.data.ast.ClassDecl","@id": "4","loc": {"@class": "apex.jorje.data.IndexLocation","@id": "5","startIndex": 59,"endIndex": 138,"line": 4,"column": 21},"modifiers": [{"@class": "apex.jorje.data.ast.Modifier$PublicModifier","@id": "7","loc": {"@class": "apex.jorje.data.IndexLocation","@id": "8","startIndex": 39,"endIndex": 45,"line": 4,"column": 1}},{"@class": "apex.jorje.data.ast.Modifier$WithSharingModifier","@id": "9","loc": {"@class": "apex.jorje.data.IndexLocation","@id": "10","startIndex": 46,"endIndex": 58,"line": 4,"column": 8}}],"name": {"@class": "apex.jorje.data.Identifiers$LocationIdentifier","@id": "11","loc": {"@class": "apex.jorje.data.IndexLocation","@id": "12","startIndex": 65,"endIndex": 70,"line": 4,"column": 27},"value": "Hello"},"typeArguments": 
[error]     at parseTextWithSpawn (/Users/matt/.nvm/versions/node/v14.16.0/lib/node_modules/prettier-plugin-apex/src/parser.js:36:11)
[error]     at Object.parse (/Users/matt/.nvm/versions/node/v14.16.0/lib/node_modules/prettier-plugin-apex/src/parser.js:489:21)
[error]     at Object.parse (/Users/matt/.nvm/versions/node/v14.16.0/lib/node_modules/prettier/index.js:13625:19)
[error]     at coreFormat (/Users/matt/.nvm/versions/node/v14.16.0/lib/node_modules/prettier/index.js:14899:14)
[error]     at format (/Users/matt/.nvm/versions/node/v14.16.0/lib/node_modules/prettier/index.js:15131:14)
[error]     at Object.formatWithCursor (/Users/matt/.nvm/versions/node/v14.16.0/lib/node_modules/prettier/index.js:57542:12)
[error]     at format (/Users/matt/.nvm/versions/node/v14.16.0/lib/node_modules/prettier/bin-prettier.js:15883:14)
[error]     at Object.formatFiles (/Users/matt/.nvm/versions/node/v14.16.0/lib/node_modules/prettier/bin-prettier.js:16067:16)
[error]     at Object.run (/Users/matt/.nvm/versions/node/v14.16.0/lib/node_modules/prettier/bin-prettier.js:16538:14)
[error]     at Object.<anonymous> (/Users/matt/.nvm/versions/node/v14.16.0/lib/node_modules/prettier/bin-prettier.js:16553:5)
```

```zsh
❯ apex-ast-serializer -f json -i -p -l "classes/Hello.cls"
{"apex.jorje.semantic.compiler.parser.ParserOutput": {
  "@id": "1",
  "internalErrors": [],
  "parseErrors": [],
  "unit": {
    "@class": "apex.jorje.data.ast.CompilationUnit$ClassDeclUnit",
    "@id": "3",
    "body": {
      "@class": "apex.jorje.data.ast.ClassDecl",
      "@id": "4",
      "loc": {
        "@class": "apex.jorje.data.IndexLocation",
        "@id": "5",
        "startIndex": 59,
        "endIndex": 138,
        "line": 4,
        "column": 21
      },
      "modifiers": [
        {
          "@class": "apex.jorje.data.ast.Modifier$PublicModifier",
          "@id": "7",
          "loc": {
            "@class": "apex.jorje.data.IndexLocation",
            "@id": "8",
            "startIndex": 39,
            "endIndex": 45,
            "line": 4,
            "column": 1
          }
        },
        {
          "@class": "apex.jorje.data.ast.Modifier$WithSharingModifier",
          "@id": "9",
          "loc": {
            "@class": "apex.jorje.data.IndexLocation",
            "@id": "10",
            "startIndex": 46,
            "endIndex": 58,
            "line": 4,
            "column": 8
          }
        }
      ],
      "name": {
        "@class": "apex.jorje.data.Identifiers$LocationIdentifier",
        "@id": "11",
        "loc": {
          "@class": "apex.jorje.data.IndexLocation",
          "@id": "12",
          "startIndex": 65,
          "endIndex": 70,
          "line": 4,
          "column": 27
        },
        "value": "Hello"
      },
      "typeArguments": Exception in thread "main" com.thoughtworks.xstream.converters.ConversionException: No converter available
---- Debugging information ----
message             : No converter available
type                : java.util.Optional
converter           : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
message[1]          : Unable to make field private static final java.util.Optional java.util.Optional.EMPTY accessible: module java.base does not "opens java.util" to unnamed module @324e4822
-------------------------------
        at com.thoughtworks.xstream.core.DefaultConverterLookup.lookupConverterForType(DefaultConverterLookup.java:88)
        at com.thoughtworks.xstream.XStream$1.lookupConverterForType(XStream.java:479)
        at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:48)
        at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:270)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:174)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:262)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:90)
        at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
        at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
        at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:270)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:174)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:262)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:90)
        at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
        at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
        at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:270)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:174)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:262)
        at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:90)
        at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
        at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
        at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
        at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:82)
        at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
        at com.thoughtworks.xstream.XStream.marshal(XStream.java:1255)
        at com.thoughtworks.xstream.XStream.marshal(XStream.java:1244)
        at com.thoughtworks.xstream.XStream.toXML(XStream.java:1217)
        at net.dangmai.serializer.Apex.getAST(Apex.java:85)
        at net.dangmai.serializer.Apex.main(Apex.java:135)
```

**Additional information**:

- OS: macOS Big Sur
- Version: 1.8.0
- Prettier: 2.2.1

**Comment by dangmai** [comment]
Interesting, thank you for the bug report. It looks like this error is Java-related. Can you check which version of Java is being used here?

**Comment by msimonis** [comment]
@dangmai Ah, it looks like that was the issue! I was using AdoptOpenJDK 16, and when switching down to 11, it appears to work correctly now.

**Comment by dangmai** [comment]
No problem man, I think there were some changes to JDK recently that disallows reflection in certain cases, that's very good to know - I think there are a few things I can do on my end to make this work with JDK 16. I will put a comment in this ticket once the next version is out so you can try it out with JDK16.

Thanks again for the bug report!

**Comment by dangmai** [comment]
Hi, I just pushed version `1.9.0` that should support JDK 16. Could you try it out and let me know if this is still a problem for you? Thanks!

**Comment by dangmai** [comment]
Awesome, thank you for checking it!
