### ISSUE TITLE
Error formatting apex documents

### ISSUE THREAD

**Issue by mara-tyrlik** [dangmai/prettier-plugin-apex#351]
Hello, I am using prettier for a while but this wee it suddenly stopper working for apex classes. I have tried several things (reinstalling everything except whole computer). but error still occurs. 

can you take a look at the error below?

running VS code on Mac os 11.2.3

```apex
["INFO" - 1:35:24 PM] Formatting /Users/...../main/default/classes/testClass.cls
["INFO" - 1:35:24 PM] Using config file at '/Users/...../.prettierrc'
["INFO" - 1:35:24 PM] Using ignore file (if present) at /Users/...../.prettierignore
["INFO" - 1:35:24 PM] File Info:
{
  "ignored": false,
  "inferredParser": "apex"
}
["INFO" - 1:35:24 PM] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 1:35:24 PM] Prettier Options:
{
  "filepath": "/Users/...../main/default/classes/testClass.cls",
  "parser": "apex",
  "trailingComma": "none",
  "tabWidth": 4,
  "useTabs": true,
  "printWidth": 140,
  "singleQuote": true,
  "endOfLine": "lf"
}
["ERROR" - 1:35:26 PM] Error formatting document.
Error: {"apex.jorje.semantic.compiler.parser.ParserOutput": {"@id": "1","internalErrors": [],"parseErrors": [],"unit": {"@class": "apex.jorje.data.ast.CompilationUnit$ClassDeclUnit","@id": "3","body": {"@class": "apex.jorje.data.ast.ClassDecl","@id": "4","loc": {"@class": "apex.jorje.data.IndexLocation","@id": "5","startIndex": 20,"endIndex": 70,"line": 1,"column": 21},"modifiers": [{"@class": "apex.jorje.data.ast.Modifier$PublicModifier","@id": "7","loc": {"@class": "apex.jorje.data.IndexLocation","@id": "8","startIndex": 0,"endIndex": 6,"line": 1,"column": 1}},{"@class": "apex.jorje.data.ast.Modifier$WithSharingModifier","@id": "9","loc": {"@class": "apex.jorje.data.IndexLocation","@id": "10","startIndex": 7,"endIndex": 19,"line": 1,"column": 8}}],"name": {"@class": "apex.jorje.data.Identifiers$LocationIdentifier","@id": "11","loc": {"@class": "apex.jorje.data.IndexLocation","@id": "12","startIndex": 26,"endIndex": 35,"line": 1,"column": 27},"value": "testClass"},"typeArguments": 
	at parseTextWithSpawn (/Users/...../node_modules/prettier-plugin-apex/src/parser.js:36:11)
	at Object.parse (/Users/...../node_modules/prettier-plugin-apex/src/parser.js:489:21)
	at Object.parse (/User/...../node_modules/prettier/index.js:13625:19)
	at coreFormat (/Users/...../node_modules/prettier/index.js:14899:14)
	at format (/Users/...../node_modules/prettier/index.js:15131:14)
	at /Users/...../node_modules/prettier/index.js:57542:12
	at Object.format (/Users/...../node_modules/prettier/index.js:57562:12)
	at t.default.<anonymous> (/Users/...../.vscode/extensions/esbenp.prettier-vscode-6.3.2/dist/extension.js:1:16897)
	at Generator.next (<anonymous>)
	at s (/Users/...../.vscode/extensions/esbenp.prettier-vscode-6.3.2/dist/extension.js:1:9119)
["INFO" - 1:35:26 PM] Formatting completed in 573.345693ms.
```

**Comment by dangmai** [comment]
Hi, this is likely a duplicate of https://github.com/dangmai/prettier-plugin-apex/issues/350 You can try downgrading JDK to a lower version and it should work again. I'm working on a more permanent fix for newer JDK versions

**Comment by mara-tyrlik** [comment]
With java 11 works, thank you :)

**Comment by dangmai** [comment]
Hi, I just pushed version `1.9.0` that should support JDK 16. Could you try it out and let me know if this is still a problem for you? Thanks!
