### ISSUE TITLE
Need to support foreach and for statements with no blocks

### ISSUE THREAD

**Issue by praksb** [dangmai/prettier-plugin-apex#36]
Trying to format the following code will thrown an error.

public class ForEachStatement {
    public void testNoBlock() {
        for (String s: stringSet);
    }
}

[error] ForEachStatement.cls: TypeError: Cannot read property '@class' of undefined
[error]     at FastPath.call (/usr/local/lib/node_modules/prettier/bin-prettier.js:13360:18)
[error]     at Object.handleForLoop [as apex.jorje.data.ast.Stmnt$ForLoop] (/usr/local/lib/node_modules/prettier-plugin-apex/src/printer.js:1925:30)
[error]     at genericPrint (/usr/local/lib/node_modules/prettier-plugin-apex/src/printer.js:2310:34)
[error]     at innerPath (/usr/local/lib/node_modules/prettier-plugin-apex/src/printer.js:2332:5)
[error]     at printComments (/usr/local/lib/node_modules/prettier-plugin-apex/src/comments.js:414:22)
[error]     at printGenerically (/usr/local/lib/node_modules/prettier-plugin-apex/src/printer.js:2331:15)
[error]     at FastPath.map (/usr/local/lib/node_modules/prettier/bin-prettier.js:13430:21)
[error]     at Object.handleBlockStatement [as apex.jorje.data.ast.Stmnt$BlockStmnt] (/usr/local/lib/node_modules/prettier-plugin-apex/src/printer.js:620:30)
[error]     at genericPrint (/usr/local/lib/node_modules/prettier-plugin-apex/src/printer.js:2310:34)
[error]     at innerPath (/usr/local/lib/node_modules/prettier-plugin-apex/src/printer.js:2332:5)

**Comment by praksb** [comment]
public class ForLoopStatement {
    public void controlMethodCall() {
        for (;; voidCall());
    }
}

Will also throw an error.
