### ISSUE TITLE
Error formatting Apex document 

### ISSUE THREAD

**Issue by Zerony** [dangmai/prettier-plugin-apex#378]
```sh
# Prettier options (if any):
Standard Salesforce
{
  "trailingComma": "none",
  "overrides": [
    {
      "files": "**/lwc/**/*.html",
      "options": { "parser": "lwc" }
    },
    {
      "files": "*.{cmp,page,component}",
      "options": { "parser": "html" }
    }
  ]
}

```

**Input:**
Attempt to format Apex code. JS formatting works well. 
```apex
// code snippet
```

**Actual output:**
Error
```
["ERROR" - 11:39:11 PM] Error formatting document.
Error: spawnSync /Users/ovasch/Documents/Projects/sforce.com-ci-sfdx/node_modules/prettier-plugin-apex/vendor/apex-ast-serializer/bin/apex-ast-serializer EPIPE
	at Object.spawnSync (internal/child_process.js:1067:20)
	at spawnSync (child_process.js:611:24)
	at parseTextWithSpawn (/Users/ovasch/Documents/Projects/sforce.com-ci-sfdx/node_modules/prettier-plugin-apex/src/parser.js:25:27)
	at Object.parse (/Users/ovasch/Documents/Projects/sforce.com-ci-sfdx/node_modules/prettier-plugin-apex/src/parser.js:489:21)
	at Object.parse$a [as parse] (/Users/ovasch/Documents/Projects/sforce.com-ci-sfdx/node_modules/prettier/index.js:14892:19)
	at coreFormat (/Users/ovasch/Documents/Projects/sforce.com-ci-sfdx/node_modules/prettier/index.js:16425:16)
	at formatWithCursor$1 (/Users/ovasch/Documents/Projects/sforce.com-ci-sfdx/node_modules/prettier/index.js:16665:14)
	at /Users/ovasch/Documents/Projects/sforce.com-ci-sfdx/node_modules/prettier/index.js:60922:12
	at Object.format (/Users/ovasch/Documents/Projects/sforce.com-ci-sfdx/node_modules/prettier/index.js:60942:12)
	at t.default.<anonymous> (/Users/ovasch/.vscode/extensions/esbenp.prettier-vscode-6.4.0/dist/extension.js:1:16819)
	at Generator.next (<anonymous>)
	at s (/Users/ovasch/.vscode/extensions/esbenp.prettier-vscode-6.4.0/dist/extension.js:1:9119)
```

**Expected output:**

```apex
// code snippet
```

**Additional information (please fill this out)**:

- OS: OS X
- Version: 10.14.6

**Comment by dangmai** [comment]
Which version of Prettier Apex are you running? You can run this in your project to check it out (if you're using NPM):

```
npm ls prettier-plugin-apex
```

This is likely because you're using an older version that doesn't support the Java version that OS X ships with.

**Comment by Zerony** [comment]
Thank you for your response! 

prettier-plugin-apex@1.9.1 

Will try to check my java version.

**Comment by Zerony** [comment]
I've upgraded java version to 8.221, still see same error.

**Comment by Zerony** [comment]
Similar issue found on Windows 10 machine

`Error:
at parseTextWithSpawn (d:\Projects\SCyber_regular\node_modules\prettier-plugin-apex\src\parser.js:36:11)
at Object.parse (d:\Projects\SCyber_regular\node_modules\prettier-plugin-apex\src\parser.js:489:21)
at Object.parse (d:\Projects\SCyber_regular\node_modules\prettier\index.js:9739:19)
at coreFormat (d:\Projects\SCyber_regular\node_modules\prettier\index.js:13252:23)
at format (d:\Projects\SCyber_regular\node_modules\prettier\index.js:13510:73)
at formatWithCursor (d:\Projects\SCyber_regular\node_modules\prettier\index.js:13526:12)
at d:\Projects\SCyber_regular\node_modules\prettier\index.js:44207:15
at Object.format (d:\Projects\SCyber_regular\node_modules\prettier\index.js:44226:12)
at t.default.<anonymous> (c:\Users\Alexandr\.vscode\extensions\esbenp.prettier-vscode-6.3.2\dist\extension.js:1:16897)
at Generator.next (<anonymous>)
at s (c:\Users\Alexandr\.vscode\extensions\esbenp.prettier-vscode-6.3.2\dist\extension.js:1:9119)`

**Comment by dangmai** [comment]
Ah I see, the issue is that we dropped support for Java 8 in Prettier Apex 1.9.0. Please look at this issue: https://github.com/dangmai/prettier-plugin-apex/issues/357 for more context and workarounds (easiest one is to update your JDK to version 11).
