### ISSUE TITLE
Error formatting document

### ISSUE THREAD

**Issue by pardhav** [dangmai/prettier-plugin-apex#392]
Hi there,

I keep getting this error **Error formatting document** below is the total output, this happens with every Apex class.

```bat

["INFO" - 5:31:51 pm] Extension Name: esbenp.prettier-vscode.
["INFO" - 5:31:51 pm] Extension Version: 8.0.1.
["INFO" - 5:32:02 pm] Formatting d:\Salesforce Orgs\Test\force-app\main\default\classes\Test.cls
["INFO" - 5:32:03 pm] Using config file at 'd:\Salesforce Orgs\Test\.prettierrc'
["INFO" - 5:32:03 pm] Using ignore file (if present) at d:\Salesforce Orgs\Test\.prettierignore
["INFO" - 5:32:03 pm] File Info:
{
  "ignored": false,
  "inferredParser": "apex"
}
["INFO" - 5:32:03 pm] Detected local configuration (i.e. .prettierrc or .editorconfig), VS Code configuration will not be used
["INFO" - 5:32:03 pm] Prettier Options:
{
  "filepath": "d:\\Salesforce Orgs\\Test\\force-app\\main\\default\\classes\\Test.cls",
  "parser": "apex",
  "trailingComma": "none"
}
["ERROR" - 5:32:03 pm] Error formatting document.
Error: 
	at parseTextWithSpawn (d:\Salesforce Orgs\Test\node_modules\prettier-plugin-apex\src\parser.js:36:11)
	at Object.parse (d:\Salesforce Orgs\Test\node_modules\prettier-plugin-apex\src\parser.js:497:21)
	at Object.parse$a [as parse] (d:\Salesforce Orgs\Test\node_modules\prettier\index.js:13684:19)
	at coreFormat (d:\Salesforce Orgs\Test\node_modules\prettier\index.js:15215:16)
	at formatWithCursor$1 (d:\Salesforce Orgs\Test\node_modules\prettier\index.js:15455:14)
	at d:\Salesforce Orgs\Test\node_modules\prettier\index.js:60228:12
	at Object.format (d:\Salesforce Orgs\Test\node_modules\prettier\index.js:60248:12)
	at t.default.<anonymous> (c:\Users\pardh\.vscode\extensions\esbenp.prettier-vscode-8.0.1\dist\extension.js:1:14555)
	at Generator.next (<anonymous>)
	at i (c:\Users\pardh\.vscode\extensions\esbenp.prettier-vscode-8.0.1\dist\extension.js:1:7003)
["INFO" - 5:32:03 pm] Formatting completed in 26.079ms.
```

Other info:
```shell
$ npm ls prettier-plugin-apex
salesforce-app@1.0.0 D:\Salesforce Orgs\Test
-- prettier-plugin-apex@1.10.0`
```

```bat
C:\***\***>java` --version
java 11.0.11 2021-04-20 LTS
```
Thanks in Advance!

**Comment by dangmai** [comment]
Hi, thanks for opening the issue - your set up looks correct here, so there might be something else going on. Could you try running this using the Command Prompt (not Powershell) and paste the result here please?

```bat
cd "d:\Salesforce Orgs\Test"
echo %JAVA_HOME%
npx prettier force-app\main\default\classes\Test.cls
```

**Comment by pardhav** [comment]
Hi, @dangmai. The above command showed that vs code was pointed to the wrong java version, setting it to the correct version and restarting my laptop solved the issue, formatting works fine now.

**Comment by dangmai** [comment]
I'm glad to hear that it worked out, thanks for using Prettier Apex!

**Comment by changyeamoon** [comment]
@pardhav How do you switch your vs code java?
