### ISSUE TITLE
Error when formatting a large project

### ISSUE THREAD

**Issue by abeaugustijn** [dangmai/prettier-plugin-apex#460]
Hi,

I've been trying to implement code formatting into our code base with this package. It has been working very well for a smaller package, but now that I try to run the formatting on a larger one it fails without giving any specific error message.

Everything seems to work fine for the most part, but at some point it just exits. I can't tell if it fails to format a specific file or that it has formatted all files and then just throws an error.

Thanks in advance for taking a look :)

Terminal output:
```
x\logic\force-app\x\lwc\x\x.js 2ms
x\logic\force-app\x\lwc\x\__tests__\x.test.js 8ms
x\logic\force-app\x\lwc\x\x.html 5ms
x\logic\force-app\x\lwc\x\x.js 11ms
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! x-salesforce@ x:format:run: `prettier --write ".\x\**\{*.cls,*.trigger,*.js,*.html,*.cmp}" --apex-standalone-parser built-in-autolaunched`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the x-salesforce@ x:format:run script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\x\AppData\Roaming\npm-cache\_logs\2022-01-21T11_14_11_467Z-debug.log
C:\Dev\MSR\Salesforce [build/faster-formatting +0 ~2221 -0 !]>
```

Error log created by NPM:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'x:format:run'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v14.17.0
4 verbose run-script [
4 verbose run-script   'prex:format:run',
4 verbose run-script   'x:format:run',
4 verbose run-script   'postx:format:run'
4 verbose run-script ]
5 info lifecycle x-salesforce@~prex:format:run: x-salesforce@
6 info lifecycle x-salesforce@~x:format:run: x-salesforce@
7 verbose lifecycle x-salesforce@~x:format:run: unsafe-perm in lifecycle true
8 verbose lifecycle x-salesforce@~x:format:run: PATH: x
9 verbose lifecycle x-salesforce@~x:format:run: CWD: C:\Dev\MSR\Salesforce
10 silly lifecycle x-salesforce@~x:format:run: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'prettier --write ".\\x\\**\\{*.cls,*.trigger,*.js,*.html,*.cmp}" --apex-standalone-parser built-in-autolaunched'
10 silly lifecycle ]
11 silly lifecycle x-salesforce@~x:format:run: Returned: code: 2  signal: null
12 info lifecycle x-salesforce@~x:format:run: Failed to exec x:format:run script
13 verbose stack Error: x-salesforce@ x:format:run: `prettier --write ".\x\**\{*.cls,*.trigger,*.js,*.html,*.cmp}" --apex-standalone-parser built-in-autolaunched`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:376:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:376:20)
13 verbose stack     at maybeClose (internal/child_process.js:1055:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid x-salesforce@
15 verbose cwd C:\Dev\MSR\Salesforce
16 verbose Windows_NT 10.0.19044
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "x:format:run"
18 verbose node v14.17.0
19 verbose npm  v6.14.13
20 error code ELIFECYCLE
21 error errno 2
22 error x-salesforce@ x:format:run: `prettier --write ".\x\**\{*.cls,*.trigger,*.js,*.html,*.cmp}" --apex-standalone-parser built-in-autolaunched`
22 error Exit status 2
23 error Failed at the x-salesforce@ x:format:run script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

**Note**: In this example, I am using the `prettier-plugin-apex-autolaunch` package, but the same error occurs when using the original one.

**Comment by dangmai** [comment]
Hi, thanks for raising this issue, I didn't even know about the existence of `prettier-plugin-apex-autolaunch`, it's pretty cool :)

Unfortunately the current stack trace is not enough for me to debug this issue as-is, and I'd need your help in further debugging this. First off, your script is formatting a lot of different file formats (`cls, trigger, js, html, cmp`), some of which are not handled by Prettier Apex. Could you take off `js, html, cmp` just to make sure Prettier Apex is the culprit here?

The next thing to try is to partition out the Apex files to see if one file in particular is causing this issue, you can manually binary search through your files to determine this - leave half of the files in your folder to see if the error occurs, then leave the other half, then continue drilling down :)

Looking forward to further debugging this!

**Comment by abeaugustijn** [comment]
Hi, thanks for the quick response.
Yeah pretty cool package, stumbled upon it while looking for this one. Maybe something to incorperate?

Great suggestion, I ran it with only cls and trigger files and no error :)
So I guess I got to start looking elsewhere.

I'll close this issue now
