### ISSUE TITLE
Old error while running with JDK 17

### ISSUE THREAD

**Issue by imTachu** [dangmai/prettier-plugin-apex#490]
I just upgraded from JDK 11 to JDK 17. I have prettier and this plugin installed globally, but also tried locally within a project. 
(This looks exactly like issue #350 but that one refers to JDK 16)

Input:

```apex
public with sharing class Hello {
    public Hello() {
        System.debug('Hello world');
    }
}
```
Error:

```
❯ prettier --write "classes/Hello.cls"  

Error: {"apex.jorje.semantic.compiler.parser.ParserOutput": {"@id": "1","internalErrors": [],"parseErrors": [],"unit": {"@class": "apex.jorje.data.ast.CompilationUnit$ClassDeclUnit","@id": "3","body": {"@class": "apex.jorje.data.ast.ClassDecl","@id": "4","loc": {"@class": "apex.jorje.data.IndexLocation","@id": "5","startIndex": 572,"endIndex": 2514,"line": 14,"column": 9},"modifiers": [{"@class": "apex.jorje.data.ast.Modifier$Annotation","@id": "7","loc": {"@class": "apex.jorje.data.IndexLocation","@id": "8","startIndex": 556,"endIndex": 563,"line": 13,"column": 1},"name": {"@class": "apex.jorje.data.Identifiers$LocationIdentifier","@id": "9","loc": {"@class": "apex.jorje.data.IndexLocation","@id": "10","startIndex": 557,"endIndex": 563,"line": 13,"column": 2},"value": "IsTest"},"parameters": []},{"@class": "apex.jorje.data.ast.Modifier$PrivateModifier","@id": "11","loc": {"@class": "apex.jorje.data.IndexLocation","@id": "12","startIndex": 564,"endIndex": 571,"line": 14,"column": 1}}],"name": {"@class": "apex.jorje.data.Identifiers$LocationIdentifier","@id": "13","loc": {"@class": "apex.jorje.data.IndexLocation","@id": "14","startIndex": 578,"endIndex": 618,"line": 14,"column": 15},"value": "InvocableCalculateSolutionSearchTermsTst"},"typeArguments":
[error]     at parseTextWithSpawn (/Users/lorena/repos/picnic-salesforce-customer-success/node_modules/prettier-plugin-apex/src/parser.js:36:11)
[error]     at Object.parse (/Users/lorena/repos/picnic-salesforce-customer-success/node_modules/prettier-plugin-apex/src/parser.js:489:21)
[error]     at Object.parse (/Users/lorena/repos/picnic-salesforce-customer-success/node_modules/prettier/index.js:13575:19)
[error]     at coreFormat (/Users/lorena/repos/picnic-salesforce-customer-success/node_modules/prettier/index.js:14851:25)
[error]     at format (/Users/lorena/repos/picnic-salesforce-customer-success/node_modules/prettier/index.js:15073:14)
[error]     at formatWithCursor (/Users/lorena/repos/picnic-salesforce-customer-success/node_modules/prettier/index.js:15090:12)
[error]     at Object.formatWithCursor (/Users/lorena/repos/picnic-salesforce-customer-success/node_modules/prettier/index.js:54691:12)
[error]     at format (/Users/lorena/repos/picnic-salesforce-customer-success/node_modules/prettier/bin-prettier.js:15851:14)
[error]     at Object.formatFiles (/Users/lorena/repos/picnic-salesforce-customer-success/node_modules/prettier/bin-prettier.js:16035:16)
[error]     at Object.run (/Users/lorena/repos/picnic-salesforce-customer-success/node_modules/prettier/bin-prettier.js:16508:14)
```

**Additional information**:

- OS: MacOS Monterey
- Version: 1.5.7

**Comment by imTachu** [comment]
Ah, I see now that this was fixed in version `1.9.0`, will try to upgrade first

**Comment by imTachu** [comment]
Nvm, fixed after the upgrade.

**Comment by dangmai** [comment]
I'm glad you got it working!
