### ISSUE TITLE
apex-ast-serializer EPIPE

### ISSUE THREAD

**Issue by gonardfreeman** [dangmai/prettier-plugin-apex#512]
Getting error while trying to format `.cls` file in VSCode (on save or cmd+p format document)
Also same error if you run it directly from prettier cli

**Additional information (please fill this out)**:
prettier-plugin-apex: 1.10.0
prettier: 2.6.2

nodeJS v16.14.2
npm 8.7.0
- OS: macOS Monterey (M1)
- Version: 12.3.1

**Comment by dangmai** [comment]
Hi, could you provide more details about the error? Stacktrace would be really helpful if you can see it from the CLI. Your Java version would also be helpful for debugging.

**Comment by gonardfreeman** [comment]
Hi!
here stack trace

```
./node_modules/.bin/prettier --write "force-app/main/default/classes/CA_DataLayer.cls" --loglevel debug
[debug] normalized argv: {"_":["force-app/main/default/classes/CA_DataLayer.cls"],"color":true,"editorconfig":true,"write":true,"loglevel":"debug","configPrecedence":"cli-override","debugRepeat":0,"ignorePath":".prettierignore","plugins":[],"pluginSearchDirs":[],"__raw":{"_":["force-app/main/default/classes/CA_DataLayer.cls"],"color":true,"editorconfig":true,"write":true,"loglevel":"debug","config-precedence":"cli-override","debug-repeat":0,"ignore-path":".prettierignore","plugin":[],"plugin-search-dir":[]}}
[debug] resolve config from 'force-app/main/default/classes/CA_DataLayer.cls'
[debug] loaded options `{"trailingComma":"none","tabWidth":4,"singleQuote":false,"printWidth":120}`
[debug] applied config-precedence (cli-override): {"printWidth":120,"singleQuote":false,"tabWidth":4,"trailingComma":"none"}
force-app/main/default/classes/CA_DataLayer.cls/Users/dimabondarenko/Developer/sfdx_projects/calendar/ca-lwc/node_modules/prettier-plugin-apex/vendor/apex-ast-serializer/bin/apex-ast-serializer

[error] force-app/main/default/classes/CA_DataLayer.cls: Error: spawnSync /Users/dimabondarenko/Developer/sfdx_projects/calendar/ca-lwc/node_modules/prettier-plugin-apex/vendor/apex-ast-serializer/bin/apex-ast-serializer EPIPE
[error]     at Object.spawnSync (node:internal/child_process:1111:20)
[error]     at spawnSync (node:child_process:814:24)
[error]     at parseTextWithSpawn (/Users/dimabondarenko/Developer/sfdx_projects/calendar/ca-lwc/node_modules/prettier-plugin-apex/src/parser.js:26:27)
[error]     at Object.parse (/Users/dimabondarenko/Developer/sfdx_projects/calendar/ca-lwc/node_modules/prettier-plugin-apex/src/parser.js:498:21)
[error]     at Object.parse (/Users/dimabondarenko/Developer/sfdx_projects/calendar/ca-lwc/node_modules/prettier/index.js:7361:23)
[error]     at coreFormat (/Users/dimabondarenko/Developer/sfdx_projects/calendar/ca-lwc/node_modules/prettier/index.js:8672:18)
[error]     at formatWithCursor2 (/Users/dimabondarenko/Developer/sfdx_projects/calendar/ca-lwc/node_modules/prettier/index.js:8864:18)
[error]     at Object.formatWithCursor (/Users/dimabondarenko/Developer/sfdx_projects/calendar/ca-lwc/node_modules/prettier/index.js:39174:12)
[error]     at format (/Users/dimabondarenko/Developer/sfdx_projects/calendar/ca-lwc/node_modules/prettier/cli.js:12043:24)
[error]     at formatFiles2 (/Users/dimabondarenko/Developer/sfdx_projects/calendar/ca-lwc/node_modules/prettier/cli.js:12122:20)
```

and version of java 1.8.0_331

**Comment by dangmai** [comment]
I see, that's because starting at version 1.9.0 this library has dropped support for Java < 11 (because Java 1.8 has been EOLed and no longer receive support). Please update to Java >= 11 and this should be resolved.

More context in another ticket here: https://github.com/dangmai/prettier-plugin-apex/issues/357

**Comment by gonardfreeman** [comment]
Thanks @dangmai !
