### ISSUE TITLE
showing error on apex class created from sfdx force:apex:class:create

### ISSUE THREAD

**Issue by chongwang87** [dangmai/prettier-plugin-apex#700]
Hi there, im trying to setup prettier to lint the apex code. I have prettier & prettier-plugin-apex installed, I also created an apex class using `sfdx force:apex:class:create` command. When I try to `prettier --check` the apex files, it throw me an error without much info what's going wrong. Hence seeking advise here on how we can debug or resolve the issue.
Thanks in advance.

```sh
sfdx force:apex:class:create -n MyClass -d classes
```

```apex
// force-app/main/default/classes/MyClass.cls
public with sharing class MyClass {
    public MyClass() {

    }
}
```

**Actual output:**

```
// "prettier:verify": "prettier --check \"**/*.{cls,cmp,component,css,html,js,json,md,page,trigger,xml,yaml,yml}\"",

force-app/main/default/classes/MyClass.cls
[error] force-app/main/default/classes/MyClass.cls: Error
[error]     at parseTextWithSpawn (/Users/ckoo/Development/pharma-pxp/pxp-platform-salesforce/node_modules/prettier-plugin-apex/dist/src/parser.js:56:15)
[error]     at Object.parse (/Users/ckoo/Development/pharma-pxp/pxp-platform-salesforce/node_modules/prettier-plugin-apex/dist/src/parser.js:460:25)
[error]     at Object.parse (/Users/ckoo/Development/pharma-pxp/pxp-platform-salesforce/node_modules/prettier/index.js:7334:23)
[error]     at coreFormat (/Users/ckoo/Development/pharma-pxp/pxp-platform-salesforce/node_modules/prettier/index.js:8645:18)
[error]     at formatWithCursor2 (/Users/ckoo/Development/pharma-pxp/pxp-platform-salesforce/node_modules/prettier/index.js:8837:18)
[error]     at Object.formatWithCursor (/Users/ckoo/Development/pharma-pxp/pxp-platform-salesforce/node_modules/prettier/index.js:37229:12)
[error]     at format (/Users/ckoo/Development/pharma-pxp/pxp-platform-salesforce/node_modules/prettier/cli.js:14748:24)
[error]     at formatFiles2 (/Users/ckoo/Development/pharma-pxp/pxp-platform-salesforce/node_modules/prettier/cli.js:14860:22)
[error]     at async main (/Users/ckoo/Development/pharma-pxp/pxp-platform-salesforce/node_modules/prettier/cli.js:15077:5)
[error]     at async Object.run (/Users/ckoo/Development/pharma-pxp/pxp-platform-salesforce/node_modules/prettier/cli.js:15024:5)
```

**Additional information (please fill this out)**:

- OS: OS X Big Sur 11.7.1
- Node v16.18.0
- "prettier": "^2.7.1",
- "prettier-plugin-apex": "^1.11.0"

**Comment by dangmai** [comment]
Hello, thanks for opening the bug report. I think I need more details here to debug this issue, if possible could you paste the code you're trying to format here?

Also, another thing to paste here is the result for the following 2 commands:

```bash
echo $JAVA_HOME
java -version
```

**Comment by chongwang87** [comment]
Hi, sorry for later reply.
there is no output from my `echo $JAVA_HOME` command 

```bash
java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_292-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.292-b10, mixed mode)
```

**Comment by dangmai** [comment]
Hello, Prettier Apex only supports Java >= 11, and currently you're running Java 8. Please update to a supported Java version, and if it still doesn't work, feel free to open another ticket!
