### ISSUE TITLE
Error running on class because of SOQL using DISTANCE and GEOLOCATION

### ISSUE THREAD

**Issue by renatoliveira** [dangmai/prettier-plugin-apex#90]
**Input:**

Class with many methods, but one in particular causes this error (I commented it out, and it is this one that causes Prettier to error):

```apex
@AuraEnabled
public static List<Lead> getNearbyLeads (Decimal lat, Decimal lon) {
    return [
        SELECT
            Id
            ,Name
            ,Address
            ,Latitude
            ,Longitude
            ,Street
            ,PostalCode
        FROM Lead
        WHERE DISTANCE(Address, GEOLOCATION(:lat, :lon), 'km') < 5
    ];
}
```

**Output:**

No output

**Additional information**:

```log
[error] force-app/main/default/classes/CheckInController.cls: TypeError: Cannot read property '$' of undefined
[error]     at FastPath.call (/Users/renatoliveira/Desktop/mycompany/theproject/node_modules/prettier/bin-prettier.js:13405:18)
[error]     at Object.handleGeolocationLiteral [as apex.jorje.data.soql.Geolocation$GeolocationLiteral] (/Users/renatoliveira/Desktop/mycompany/theproject/node_modules/prettier-plugin-apex/src/printer.js:1875:24)
[error]     at genericPrint (/Users/renatoliveira/Desktop/mycompany/theproject/node_modules/prettier-plugin-apex/src/printer.js:2736:34)
[error]     at Object.printGenerically [as print] (/Users/renatoliveira/Desktop/mycompany/theproject/node_modules/prettier-plugin-apex/src/printer.js:2757:15)
[error]     at callPluginPrintFunction (/Users/renatoliveira/Desktop/mycompany/theproject/node_modules/prettier/bin-prettier.js:13622:18)
[error]     at /Users/renatoliveira/Desktop/mycompany/theproject/node_modules/prettier/bin-prettier.js:13573:16
[error]     at Object.printComments (/Users/renatoliveira/Desktop/mycompany/theproject/node_modules/prettier/bin-prettier.js:13295:17)
[error]     at printGenerically (/Users/renatoliveira/Desktop/mycompany/theproject/node_modules/prettier/bin-prettier.js:13572:22)
[error]     at FastPath.call (/Users/renatoliveira/Desktop/mycompany/theproject/node_modules/prettier/bin-prettier.js:13409:16)
[error]     at Object.handleDistanceFunctionExpression [as apex.jorje.data.soql.DistanceFunctionExpr] (/Users/renatoliveira/Desktop/mycompany/theproject/node_modules/prettier-plugin-apex/src/printer.js:1862:26)
```

- OS: macOS
- Version: 1.18.2

**Comment by dangmai** [comment]
Thank you for the bug report, this is indeed an issue and I have fixed it in the `master` branch. It will be included in the next release.
